trigger:
  - master

schedules:
  - cron: "0 * * * *" # Every hour
    displayName: Hourly Check
    branches:
      include:
        - master
    always: "true"

pool:
  name: "selfhosted" # Your self-hosted Windows agent pool name

variables:
  azureServiceConnection: "azureumi_serviceconnection" # Your Azure service connection name
  azureSubscriptionId: "37fd4306-4815-4e3a-a2da-6905810ccba6" # Replace with your Azure subscription ID
  workingDirectory: "Virtual Machine" # Path to your Terraform files in repo

stages:
  - stage: Terraform
    jobs:
      - job: Deploy
        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: "Terraform Deploy"
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: "ps"
              scriptLocation: "inlineScript"
              workingDirectory: $(workingDirectory)
              inlineScript: |
                Write-Host "Installing Terraform 1.9.7..."
                Invoke-WebRequest -Uri "https://releases.hashicorp.com/terraform/1.9.7/terraform_1.9.7_windows_amd64.zip" -OutFile "terraform.zip"
                Expand-Archive -Path "terraform.zip" -DestinationPath "."

                $terraformPath = "C:\terraform"
                if (-Not (Test-Path $terraformPath)) {
                  New-Item -ItemType Directory -Path $terraformPath
                }

                Move-Item -Path ".\terraform.exe" -Destination "$terraformPath\terraform.exe" -Force
                $env:Path += ";$terraformPath"

                terraform version

                # Set ARM_SUBSCRIPTION_ID environment variable for Terraform provider
                $env:ARM_SUBSCRIPTION_ID = "$(azureSubscriptionId)"

                Write-Host "Initializing Terraform..."
                terraform init -upgrade -input=false

                Write-Host "Planning Terraform..."
                terraform plan -out=tfplan

                Write-Host "Applying Terraform..."
                terraform apply -auto-approve tfplan
